### ISSUE TITLE
Make error message consistent across all backends

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/vdp#112]
**Why**
I suggest we make the error message consistent across all backends, so the frontend can present more constructive error messages to the users.

**Now**
Right now, our API error returns all error messages in the message field.
```yaml
{
    "code": 5,
    "message": "The model id mobilenetv2 you specified is not found in namespace users/91a701c2-5a50-412f-8dad-b86a50900484",
    "details": []
}
```

**How to improve**
We put a short error description in the message field (**generally less than 5 words**), and put the long description in details field. Use the above error as an example.
```yaml
{
    "code": 5,
    "message": "model not found",
    "details": ["The model id mobilenetv2 you specified is not found in namespace users/91a701c2-5a50-412f-8dad-b86a50900484"]
}
```

[ ] Pipeline-backend @pinglin
[ ] Connector-backend @pinglin
[ ] Model-backend @Phelan164
[ ] Mgmt-backend @xiaofei-du
